Style login page
veganhacktivists/fast-network pull request #10
Opened 2022-05-13 02:53 UTC by pontepotchet

Since we're not asking for a password, I didn't follow the designs exactly.
<img width="1512" alt="Screen Shot 2022-05-12 at 10 50 34 PM" src="https://user-images.githubusercontent.com/19231935/168201994-2c6070bc-6a56-4b4d-aea7-a66c056a00c6.png">

2022-05-13 02:55 UTC, pontepotchet commented on resources/views/components/secondary-button.blade.php
> +</button>
There's also a light grey button in the designs, and a yellow button. I don't think using "primary", "secondary", etc. makes sense to distinguish between them. I wanted to define just one button component and pass colors to it but there are different colors for different states.

2022-05-13 02:56 UTC, pontepotchet commented on tailwind.config.js
> +        },
Not sure about naming here, I just picked arbitrary steps for these colors...

2022-05-14 14:21 UTC, GRardB requested changes
Just some quick name changes for the buttons, I think. Happy to discuss more on Discord if you want! But otherwise, looking really good.

2022-05-14 14:21 UTC, GRardB commented on resources/views/components/secondary-button.blade.php
> +</button>
I think it's probably better to have them separate. The other thing to consider with passing in colors is that Tailwind's JIT will only pick up class names that are explicitly typed out, so we'd have to implement some sort of workaround if we were to pass in `color` as a prop to the component. 

My thoughts on the naming scheme:

Dark gray: `action-button`
Pink: `pink-button` (lol)
Yellow: `primary-button`
Light gray: `secondary-button`

Alternatively:

Dark gray: `primary-button`
Yellow: `submit-button`

We could also just use the color in the name (`dark-gray-button`, `pink-button`, etc.). It's not _super_ important, as long as we're consistent!

2022-05-14 14:21 UTC, GRardB commented on resources/views/layouts/app.blade.php
> +              @if (!isset($hideLogo))
Should this `@if` be around the whole `<div>`, or does that mess up the styling?

2022-05-14 14:21 UTC, GRardB commented on tailwind.config.js
> +        },
Fine by me!

2022-05-16 02:39 UTC, pontepotchet commented on resources/views/layouts/app.blade.php
> +              @if (!isset($hideLogo))
Yeah... because I'm using `justify-between` to space out the items on the top row (the logo and the Contact Us button), removing the whole logo `div` shifts the Contact Us button to the far left...
I just committed a change to this so that I manually align the logo to the left and the button to the right, and no more empty div.

2022-05-16 02:40 UTC, pontepotchet commented on resources/views/components/secondary-button.blade.php
> +</button>
Ok, I chose the color theme names for now!

2022-05-16 02:40 UTC, pontepotchet commented
@GRardB Updated!

2022-05-16 06:29 UTC, GRardB approved these changes

2022-05-16 12:11 UTC, merged