Implement Blade layout
veganhacktivists/fast-network pull request #8
Opened 2022-05-05 01:07 UTC by pontepotchet

2022-05-05 17:37 UTC, GRardB requested changes
Looking good! Requesting a few small changes, but I pulled down the branch and it looks great. Really good work, Dina!

2022-05-05 17:37 UTC, GRardB commented on resources/views/components/primary-button.blade.php
> +<button
Let's change this to:
```blade
<button {{ $attributes->merge([
  'type' => 'button',
  'class' => '...',
]) }}>
  {{ $slot }}
</button>
```

2022-05-05 17:37 UTC, GRardB commented on resources/views/layouts/app.blade.php
> +          @endcomponent
Let's use the newer component syntax:
```blade
<x-components.primary-button>
  Contact Us
</x-components.primary-button>
```

2022-05-05 17:37 UTC, GRardB commented on resources/views/layouts/app.blade.php
> +        <img src="{{ asset('img/footer-animals.png') }}" alt="cow, chicken, fish, pig" class="md:hidden h-8 flex items-end m-auto" />
Since this is a [decorative image](https://www.w3.org/WAI/tutorials/images/decorative/), we can leave the `alt` attribute empty.

2022-05-05 17:37 UTC, GRardB commented on resources/views/layouts/app.blade.php
> +          <x-icon-footer-logos class=" m-3 h-16" />
**Nit**: Extra space before the `m-3`

2022-05-05 17:37 UTC, GRardB commented on resources/views/layouts/app.blade.php
> +          <img src="{{ asset('img/footer-animals.png') }}" alt="cow, chicken, fish, pig" class="h-8 flex items-end float-right px-10" />
Same here re: `alt`.

2022-05-06 02:57 UTC, pontepotchet commented
@GRardB Okay, I've updated with these suggestions!

2022-05-06 07:29 UTC, GRardB approved these changes

2022-05-06 14:05 UTC, merged